nombre1 = input("Cual es tu nombre?")
edad1=input ("¿Cuantos años tienes?")
pelicula =input ("Cual es tu pelicula favorita?")
edad_num1 =int(edad1)
print(f"Hola {nombre1},Tienes {edad1},en 10 años tendras {edad_num1 + 10}, y tu pelicula favorita es {pelicula}")